language: erlang
notifications:
  recipients:
    - yuki@gnnk.net
otp_release:
  - R15B02
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "mix test"
